
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epmzmufkfoxnxpsokhoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwbXptdWZrZm94bnhwc29raG9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODc3NDUsImV4cCI6MjA1ODU2Mzc0NX0.pHSCfpHA0MhozxM9qVNO-A4HtR09zhEfi4pjaJXFkVE";

// Создаем локальное хранилище данных для мока Supabase
const localStorageDB = {
  orders: [],
  contact_requests: []
};

// Получаем сохраненные данные из localStorage при загрузке страницы
try {
  const savedOrders = localStorage.getItem('mockOrders');
  if (savedOrders) {
    localStorageDB.orders = JSON.parse(savedOrders);
  }
  
  const savedRequests = localStorage.getItem('mockContactRequests');
  if (savedRequests) {
    localStorageDB.contact_requests = JSON.parse(savedRequests);
  }
} catch (error) {
  console.error('Ошибка при загрузке данных из localStorage:', error);
}

// Создаем имитацию работы Supabase для локального тестирования
class MockSupabaseClient {
  from(table) {
    return {
      select: () => this.mockSelect(table),
      insert: (data) => this.mockInsert(table, data),
      update: (data) => this.mockUpdate(table, data),
      delete: () => this.mockDelete(table),
      order: () => ({
        select: () => this.mockSelect(table)
      }),
    };
  }

  mockSelect(table) {
    console.log(`Имитация запроса SELECT из таблицы ${table}`);
    
    // Возвращаем данные из локального хранилища
    return Promise.resolve({
      data: localStorageDB[table] || [],
      error: null,
      order: () => this.mockSelect(table),
    });
  }

  mockInsert(table, data) {
    console.log(`Имитация вставки данных в таблицу ${table}:`, data);
    
    // Добавляем ID и created_at если их нет
    const newData = {
      id: data.id || 'mock-id-' + Date.now(),
      created_at: data.created_at || new Date().toISOString(),
      ...data
    };
    
    // Добавляем данные в локальное хранилище
    localStorageDB[table] = localStorageDB[table] || [];
    localStorageDB[table].push(newData);
    
    // Сохраняем в localStorage для постоянства между перезагрузками
    if (table === 'orders') {
      localStorage.setItem('mockOrders', JSON.stringify(localStorageDB.orders));
    } else if (table === 'contact_requests') {
      localStorage.setItem('mockContactRequests', JSON.stringify(localStorageDB.contact_requests));
    }
    
    return Promise.resolve({ 
      data: { id: newData.id },
      error: null
    });
  }

  mockUpdate(table, data) {
    console.log(`Имитация обновления данных в таблице ${table}:`, data);
    return Promise.resolve({ data: null, error: null });
  }

  mockDelete(table) {
    console.log(`Имитация удаления данных из таблицы ${table}`);
    return Promise.resolve({ data: null, error: null });
  }
}

// Используем мок вместо реального клиента Supabase
export const supabase = new MockSupabaseClient();

// Для восстановления реального клиента раскомментируйте эту строку:
// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
